services:
    db:
        image: postgres:latest
        container_name: movies_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: "1234"
            POSTGRES_DB: movies
        ports:
            - "5432:5432"
        volumes:
            - db_movies_data:/var/lib/postgresql/data

volumes:
    db_movies_data: